name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  number-1:  # id of input
    description: 'The first number'
    required: true
    default: '0'
  number-2:
    description: 'The second number'
    required: true
    default: '0'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.number-1 }}
    - ${{ inputs.number-2 }}
